name: nucleusbackend
recipe: laravel
config:
  php: 7.2
  via: nginx
  database: mysql
  webroot: public
  xdebug: true
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
